### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by sthz** [nils-werner/owm-display#3]
Trying this URL (note: replace APICODE with you api code)
(http://nils-werner.github.io/owm-display/index.html#!your_ api_code_here?position=51.8428,5.8715)
I get this error: 
`https://api.darksky.net/forecast/299dddb360c2d4db9a666b5d6eb04d57?position=….8428,5.8715/51.8428,5.8715?extend=hourly&units=si&callback=futurecallback `

**Comment by nils-werner** [comment]
The correct syntax is

    https://nils-werner.github.io/owm-display/?299dddb360c2d4db9a666b5d6eb04d57&position=51.8428,5.8715

I have updated the README.

Also, make sure to include an actual error message in your issues.
