### ISSUE TITLE
DarkSky sold (shutting down API) - needs new free API weather source

### ISSUE THREAD

**Issue by ZXant** [nils-werner/owm-display#4]
DarkSky announcement on it's blog: https://blog.darksky.net/

Excerpt regarding DarkSky free Weather API: "Our API service for existing customers is not changing today, but we will no longer accept new signups. The API will continue to function through the end of 2021."

Its sad, troublesome and concerning, as myself use Weather Display with DarkSky API for website weather forecasts. 

Immediate reaction from the tech World: https://www.theverge.com/2020/4/1/21202259/android-weather-app-dark-sky-apple-purchase-api

Quick list of 'almost free' Weather APIs: https://rapidapi.com/blog/access-global-weather-data-with-these-weather-apis/

Two really free, and consistent, Weather APIs:

    - NOAA: https://www.ncdc.noaa.gov/cdo-web/webservices/v2

    Note: I may assume that using NOAA it is going direct to main weather data source; also been ".gov" might be free for long

    - YR.no: https://hjelp.yr.no/hc/en-us/articles/360001940793-Free-weather-data-service-from-Yr

    Excerpt note from YR.no API webpage: "You can get a lot of the content on Yr for free, to use for various applications and services. This is a unique offer in Europe. In other countries weather data is highly valuable and expensive."

Thanks for Weather Display,
Xant

**Comment by ZXant** [comment]
Another option, OWM - Open Weather Map.

Please, review and advice, as another weather data source provider is needed.

Thanks,
Xant

**Comment by nils-werner** [comment]
Yes, I have heard. Unfortunately, last time I checked the OWM API was rather terrible...

**Comment by ZXant** [comment]
DarkSky was a great free service, but now gone (no reason to debate). My weather website based on WeeWX, and has your work based on HighCharts and DarkSky API for forecast.

http://appnea.net/forecast/

In WeeWX forum, there are discussion, and debate, on what could be a good DarkSky replacement.

https://groups.google.com/forum/#!topic/weewx-user/m_47lX0fsIM

Two conditions:
1) Must be free
2) Must be Global

In this scenario, only two candidates shows potential: 
1- YR.no
2- OWM

Please, consider an API service replacement, and provide. Otherwise, "OWM-display" (original name) will phase-out....

**Comment by ZXant** [comment]
Another WX API option people are moving to is Aeris Weather, which is free for those that upload data to PWSweather.

Nils, apologize but your response was not clear if you will soon update to another source as to keep OWM-Display alive, and for those (like myself) that use it.

Please, advice and thank you for your continue development.

**Comment by nils-werner** [comment]
I may do it at some point, but definitely not soon, sorry.

**Comment by ZXant** [comment]
Nils

Your attention and update still needed, as DarkSky will cease API service.

Please, advice.

Thanks, ZXant

**Comment by nils-werner** [comment]
I've migrated the service to BrightSky, an open data provider that provides data from the German weather service (DWD).

Unfortunately this means that the app most likely won't work outside of Germany. Sorry about that...
